[auth]
backend = "real"

[captcha]
backend = "fake"

[chat]
backend = "fake"

[http]
cert_path = "certs/dev_cert.pem"
key_path = "certs/dev_key.pem"
address = "127.0.0.1:8443"

[log]
filter = "debug,sqlx=off,counterpoint=trace"

[user]
backend = "real"
